import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { FaPhone, FaWhatsapp } from "react-icons/fa";

import { GoogleTagManager } from '@next/third-parties/google'
 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Himachal Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const phoneNumber = "+917836098136";
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <GoogleTagManager gaId="G-3ZZS5W9MWY" />
        <Navbar />
        {children}
        <Footer />
        <div className="fixed-links whatsapp">
          <a
            href={`https://wa.me/${phoneNumber}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaWhatsapp size={25} />
          </a>
        </div>
        <div className="fixed-links phone">
          <a
            href="tel:+91 7836098136"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaPhone size={20} />
          </a>
        </div>
      </body>
    </html>
  );
}
