import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { FaPhone, FaWhatsapp } from "react-icons/fa";
import Script from "next/script"; // Use Script for proper loading of GA scripts


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Himachal Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const phoneNumber = "+917836098136";
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
   {/* Google Analytics for multiple GAIDs */}
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-3ZZS5W9MWY`}
        />
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-YM3TJ3M6G1`}
        />        
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-63LBC7QJ2F`}
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              // Initialize the first GA ID
              gtag('config', 'G-3ZZS5W9MWY');

              // Initialize the New site GA ID
              gtag('config', 'G-YM3TJ3M6G1');

              // Initialize the second GA ID
               gtag('config', 'G-63LBC7QJ2F');
            `,
          }}
        />
        {/* Hotjar Tracking Code */}
        <Script
          id="hotjar"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(h,o,t,j,a,r){
                  h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                  h._hjSettings={hjid:5160702,hjsv:6};
                  a=o.getElementsByTagName('head')[0];
                  r=o.createElement('script');r.async=1;
                  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                  a.appendChild(r);
              })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
            `,
          }}
        />        
        <Navbar />
        {children}
        <Footer />
        <div className="fixed-links whatsapp">
          <a
            href={`https://wa.me/${phoneNumber}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaWhatsapp size={25} />
          </a>
        </div>
        <div className="fixed-links phone">
          <a
            href="tel:+91 7836098136"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaPhone size={20} />
          </a>
        </div>
      </body>
    </html>
  );
}
